substitutions:
  _VERSION: "1.0.12"
  _NAME: configmap

steps:
- name: gcr.io/cloud-builders/go
  entrypoint: sh
  args:
  - -c
  - |
    mkdir -p /workspace/gopath/src/git.subiz.net
    ln -s /workspace /workspace/gopath/src/git.subiz.net/$_NAME
    cd /workspace/gopath/src/git.subiz.net/$_NAME
    go get -d -v ./...
    CGO_ENABLED=0 go build -ldflags="-s -w"

- name: gcr.io/cloud-builders/docker
  entrypoint: sh
  args:
  - -c
  - |
    docker login -u $_DOCKER_USERNAME -p $_DOCKER_PASSWORD &
    cd /workspace/gopath/src/git.subiz.net/$_NAME
    docker build -t subiz/configmap:$_VERSION . &
    wait
    docker push subiz/configmap:$_VERSION
