substitutions:
  _VERSION: "2"
  _NAME: configmap


steps:
- name: gcr.io/cloud-builders/docker
  entrypoint: sh
  args:
  - -c
  - |
    mkdir -p /workspace/gopath/src/git.subiz.net
    ln -s /workspace /workspace/gopath/src/git.subiz.net/$_NAME

- name: gcr.io/cloud-builders/go
  entrypoint: sh
  args:
  - -c
  - |
    cd /workspace/gopath/src/git.subiz.net/$_NAME
    go get -d -v ./...

- name: gcr.io/cloud-builders/go
  entrypoint: sh
  args:
  - -c
  - |
    cd /workspace/gopath/src/git.subiz.net/$_NAME
    go build

- name: gcr.io/cloud-builders/docker
  entrypoint: sh
  args:
  - -c
  - |
    cd /workspace/gopath/src/git.subiz.net/$_NAME
    docker build -t subiz/configmap:$_VERSION .

- name: gcr.io/cloud-builders/docker
  entrypoint: sh
  args:
  - -c
  - |
    docker login -u $_DOCKER_USERNAME -p $_DOCKER_PASSWORD
    docker push subiz/configmap:$_VERSION
